// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';
import { environment as defaultEnvironment } from './environment.default';

/**
 * The environment variables
 */
export const environment = {
  ...defaultEnvironment,
  production: true,
  version: env.npm_package_version,
  casBaseUrl: 'https://sso.website4sg.saint-gobain.io/cas',
  apiBaseUrl: 'https://api.saint-gobain.com',
  urlAccessToken: '/sgdsi/oauth/token',
  clientId: 'e6004158-93a9-4710-a913-02539f20e54f',
  appLanName: 'admin.website4sg.saint-gobain.com',
  gitUrl: 'https://code.website4sg.saint-gobain.io',
  supportUrl: 'https://support.website4sg.saint-gobain.io'
};
