// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';
import { environment as defaultEnvironment } from './environment.default';

/**
 * The environment variables
 */
export const environment = {
  ...defaultEnvironment,
  casBaseUrl: 'https://uat.sso.website4sg.saint-gobain.com/cas',
  appLanName: 'uat-admin.website4sg.saint-gobain.com',
  production: true,
  version: env.npm_package_version
};
