// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'Tom2',
  production: true,
  version: env.npm_package_version,
  oauthBaseUrl: 'https://cloudsso.saint-gobain.com/openam',
  apiBaseUrl: 'https://lan.api.saint-gobain.com',
  apiContextPath: '/sgdsi/lan/oauth/saml',
  clientId: 'eacedf85-20dc-4800-8452-9624ae954709',
  clientSecret: '3f0dfa8f-12aa-466d-88a8-50f6b7fa6e42',
  apiTokenPath: '/sgdsi/token',
  whiteAndYellowUrl: 'https://lan.api.saint-gobain.com/sgdsi/groupdirectory/profile/pictures',
  toolboxUrl: 'https://lan.api.saint-gobain.com/sgdsi/toolbox',
  toolboxApplicationPath: '/toolbox/applications',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  userGroup: 'APP_SGT_TOM2_USERS',
  rsmGroup: 'APP_SGT_RSM_USERS',
  adminGroup: 'APP_SGT_ADMIN',
  tom2AdminGroup: 'APP_SGT_TOM2_ADMIN',
  tom2OrderGroup: 'APP_SGT_TOM2_ORDER',
  tom2PmGroup: 'APP_SGT_TOM2_PM',
  tom2RequesterGroup: 'APP_SGT_TOM2_REQUESTER'
};
