// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'Tom2',
  production: true,
  version: env.npm_package_version,
  oauthBaseUrl: 'https://uat.cloudgateway.saint-gobain.com/openam',
  apiBaseUrl: 'https://lan.api.saint-gobain.com',
  apiContextPath: '/sgdsi/lan/oauth/uat/saml',
  clientId: '04e72807-3587-4401-87a6-caaa86866672',
  clientSecret: 'a690dc3f-597f-4011-90f5-4022e8ce59ad',
  apiTokenPath: '/sgdsi/token',
  whiteAndYellowUrl: 'https://lan.api.saint-gobain.com/sgdsi/groupdirectory/profile/pictures',
  toolboxUrl: 'https://lan.api.saint-gobain.com/sgdsi/test/toolbox',
  toolboxApplicationPath: '/toolbox/applications',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  userGroup: 'APP_SGT_TOM2_USERS',
  rsmGroup: 'APP_SGT_RSM_USERS',
  adminGroup: 'APP_SGT_ADMIN',
  tom2AdminGroup: 'APP_SGT_TOM2_ADMIN',
  tom2OrderGroup: 'APP_SGT_TOM2_ORDER',
  tom2PmGroup: 'APP_SGT_TOM2_PM',
  tom2RequesterGroup: 'APP_SGT_TOM2_REQUESTER'
};
