// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'Forget-password-ui',
  production: false,
  version: env.npm_package_version + '-dev',
  siteKey: '6LdAWIIUAAAAAH_V3bruyEkv_awm27LJ2wN6rrYV',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  oauthBaseUrl: 'https://uat.cloudgateway.saint-gobain.com/openam',
  extranetUrl: 'https://uat-employee.extranet.saint-gobain.com'
};
