// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'Forget-password-ui',
  production: true,
  version: env.npm_package_version,
  siteKey: '6LdAWIIUAAAAAH_V3bruyEkv_awm27LJ2wN6rrYV',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  oauthBaseUrl: 'https://uat.cloudgateway.saint-gobain.com/openam',
  extranetUrl: 'https://uat-employee.extranet.saint-gobain.com'
};
