// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'DeliveryOrganizer',
  production: false,
  version: env.npm_package_version + '-dev',
  oauthBaseUrl: 'https://uat.cloudgateway.saint-gobain.com/openam',
  apiBaseUrl: 'https://lan.api.saint-gobain.com',
  apiContextPath: '/sgdsi/lan/oauth/uat/saml',
  clientId: '8a9e3380-7119-4fea-9471-1848981f5d53',
  clientSecret: 'c3e88a48-6a2c-4f0e-b544-3d8d9d49c79f',
  apiTokenPath: '/sgdsi/token',
  whiteAndYellowUrl: 'https://lan.api.saint-gobain.com/sgdsi/groupdirectory/profile/pictures',
  toolboxUrl: 'https://lan.api.saint-gobain.com/sgdsi/test/toolbox',
  toolboxApplicationPath: '/toolbox/applications',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  sireneContactUrl: 'https://uat.sirene.saint-gobain.com/definition/contact',
  spoSurveyUrl: 'http://sandbox.sgt.saint-gobain.net/XSPO/search-site-survey',
  userGroup: 'APP_SGT_DO_USERS',
  modifyGroup: 'APP_SGT_DO_MODIFY',
  supervisorGroup: 'APP_SGT_DO_SUPERVISOR',
  adminGroup: 'APP_SGT_ADMIN',
  doAdminGroup: 'APP_SGT_DO_ADMIN'
};
