// `.env.ts` is generated by the `npm run env` command
import env from './.env';

/**
 * The environment variables
 */
export const environment = {
  appName: 'Sirene',
  production: true,
  version: env.npm_package_version,
  oauthBaseUrl: 'https://cloudsso.saint-gobain.com/openam',
  apiBaseUrl: 'https://lan.api.saint-gobain.com',
  apiContextPath: '/sgdsi/lan/oauth/saml',
  clientId: '996fb2f5-d15a-4ab4-a44e-753e35a1af48',
  clientSecret: '39df7b75-e042-4f95-8c07-d63b25ee4b0c',
  apiTokenPath: '/sgdsi/token',
  whiteAndYellowUrl: 'https://lan.api.saint-gobain.com/sgdsi/groupdirectory/profile/pictures',
  toolboxUrl: 'https://lan.api.saint-gobain.com/sgdsi/toolbox',
  toolboxApplicationPath: '/toolbox/applications',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  userGroup: 'APP_SGT_SIRENE_USERS',
  rsmGroup: 'APP_SGT_RSM_USERS',
  adminGroup: 'APP_SGT_ADMIN',
  sireneAdminGroup: 'APP_SGT_SIRENE_ADMIN',
  rsmProfileName: 'SGT RSM',
  doUserGroup: 'APP_SGT_DO_USERS',
  doModifyGroup: 'APP_SGT_DO_MODIFY',
  doSupervisorGroup: 'APP_SGT_DO_SUPERVISOR',
  doAdminGroup: 'APP_SGT_DO_ADMIN',
  spoUserGroup: 'APP_SGT_SPO_USERS',
  spoModifyGroup: 'APP_SGT_SPO_MODIFY',
  spoBsheetModifyGroup: 'APP_SGT_SPO_BSHEET_MODIFY',
  spoContactModifyGroup: 'APP_SGT_SPO_CONTACT_MODIFY',
  spoAdminGroup: 'APP_SGT_SPO_ADMIN'
};
