export enum ReportType {
  WAS_SCAN_REPORT = 'WAS_SCAN_REPORT',
  WAS_WEBAPP_REPORT = 'WAS_WEBAPP_REPORT',
  WAS_SCORECARD_REPORT = 'WAS_SCORECARD_REPORT',
  WAS_CATALOG_REPORT = 'WAS_CATALOG_REPORT',
  DATALIST_REPORT = 'DATALIST_REPORT'
}
