// `.env.ts` is generated by the `npm run env` command
import { env } from './.env';
import { environment as defaultEnvironment } from './environment.default';

/**
 * The environment variables
 */
export const environment = {
  ...defaultEnvironment,
  production: true,
  version: env.npm_package_version,
  oauthBaseUrl: 'https://cloudgateway.saint-gobain.com/openam',
  apiContextPath: '/sgdsi/lan/oauth/saml',
  clientId: 'ccf61bfa-32df-41b6-a3d4-6cba0f780678',
  clientSecret: '3f551e10-81b3-4510-9b5c-8e3fff1c49cb',
  toolboxUrl: 'https://lan.api.saint-gobain.com/sgdsi/toolbox'
};
